//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminFazal.Db_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tcrud
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Date_Of_Birth { get; set; }
        public string Address { get; set; }
    }
}
